version: '3'

services:
  twitter-extraction:
    build:
      context: .
    environment:
      DB_HOST: mongo
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_PORT: 27017
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: twitter
      TWITTER_SECRET_ACCESS_TOKEN: $TWITTER_SECRET_ACCESS_TOKEN
      TWITTER_CONSUMER_KEY: $TWITTER_CONSUMER_KEY
      TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
      TWITTER_CONSUMER_SECRET: $TWITTER_CONSUMER_SECRET
    command: mongod --auth
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD